services:
  redis:
    image: redis:alpine
    container_name: run-boo-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass "1234"
    volumes:
      - ./redis_data:/data
    restart: always

  redis-insight:
    image: redis/redisinsight:latest
    container_name: run-boo-redis-gui
    ports:
      - "5540:5540"
    depends_on:
      - redis