spring.application.name=run-boo
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

#supabase
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:true}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}

#Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

#JWT
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration-minutes=${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES:60}
jwt.refresh-token-expiration-days=${JWT_REFRESH_TOKEN_EXPIRATION_DAYS:14}

# Kakao OAuth
kakao.rest-api-key=${KAKAO_REST_API_KEY}
kakao.redirect-uri=${KAKAO_REDIRECT_URI}

# Google OAuth
google.client-id=${GOOGLE_CLIENT_ID}
google.client-secret=${GOOGLE_CLIENT_SECRET}
google.redirect-uri=${GOOGLE_REDIRECT_URI}

# DeepLink
app.frontend.url=${APP_FRONTEND_URL:runboo://}

#Gmail SMTP
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS_ENABLE:true}

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=${REQUEST_MAPPING_LOG_LEVEL:INFO}

#AI
spring.ai.openai.api-key=${AI_API_KEY}
spring.ai.openai.base-url=${AI_BASE_URL:https://generativelanguage.googleapis.com/v1beta/openai}
spring.ai.openai.chat.options.model=${AI_MODEL:gemini-flash-latest}


server.address=${SERVER_ADDRESS:0.0.0.0}
server.port=${SERVER_PORT:8080}

#FireBase Cloud Manager (??) ??
google.application.credentials=${GOOGLE_APPLICATION_CREDENTIALS:backSecrets/runboo-fcm.json}

VITE_API_BASE_URL=${VITE_API_BASE_URL}
admin.password=${ADMIN_PASSWORD}
